FROM confluentinc/cp-kafka-connect:latest

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest

COPY connect/register-connector.sh /usr/local/bin/register-connector.sh

CMD ["/usr/local/bin/register-connector.sh"]